---
  - name: NGINX | Install and configure
    hosts: nginx
    become: true
    vars:
      nginx_listen_port: 8080
    tasks:
      - name: Install EPEL Repo
        yum:
          name: epel-release
          state: present

      - name: NGINX | Install nginx package from epel repo
        yum:
          name: nginx
          state: latest
        notify:
          - restart nginx
        tags:
          - nginx-package
          - packages

      - name: NGINX | Create nginx config file from template
        template:
          src: templates/nginx.conf.j2  # Path to template
          dest: /etc/nginx/nginx.conf           # Change path to config dir
          owner: root   #
          group: root   # user add
          mode: 0644    #
        notify:
          - reload nginx
        tags:
          - nginx-configuration

    handlers:
      - name: restart nginx
        systemd:
          name: nginx
          state: restarted
          enabled: yes

      - name: reload nginx
        systemd:
          name: nginx
          state: reloaded
